export const Users = [
    {
      id:1,
      profilePicture: "assets/images/person/1.jpeg",
      username: "Zoey Zoey",
    },
    {
      id:2,
      profilePicture: "assets/images/person/2.jpeg",
      username: "Ngoc Anh",
    },
    {
      id:3,
      profilePicture: "assets/images/person/3.jpeg",
      username: "John Doe",
    },
    {
      id:4,
      profilePicture: "assets/images/person/4.jpeg",
      username: "Nguyễn Thành Trung",
    },
    {
      id:5,
      profilePicture: "assets/images/person/5.jpeg",
      username: "Miew Miew",
    },
    {
      id:6,
      profilePicture: "assets/images/person/6.jpeg",
      username: "Kwann",
    },
    {
      id:7,
      profilePicture: "assets/images/person/7.jpeg",
      username: "Nga Lê",
    },
    {
      id:8,
      profilePicture: "assets/images/person/8.jpeg",
      username: "Hằng",
    },
    {
      id:9,
      profilePicture: "assets/images/person/9.jpeg",
      username: "Hà Trường Giang",
    },
    {
      id:10,
      profilePicture: "assets/images/person/10.jpeg",
      username: "Thu Hà",
    },
  ];
export const Posts = [
    {
        id: 1,
        desc: "Hello!",
        photo: "assets/images/post/1.jpeg",
        date: "5 phút trước",
        userId: 1,
        like: 245,
        comment: 30,
        share: 0,
    },
    {
        id: 2,
        desc: "Lunch ^^",
        photo: "assets/images/post/2.jpeg",
        date: "15 phút trước",
        userId: 2,
        like: 138,
        comment: 25,
        share: 0,
    },
    {
        id: 3,
        desc: "Our Beloved Summer",
        photo: "assets/images/post/3.jpeg",
        date: "17 phút trước",
        userId: 2,
        like: 279,
        comment: 40,
        share: 1,
    },
    {
        id: 4,
        desc: "𝐈 𝐬𝐰𝐞𝐚𝐫, 𝐛𝐥𝐚𝐜𝐤 𝐜𝐚𝐭 𝐚𝐫𝐞 𝐬𝐨 𝐜𝐮𝐭𝐞. 🖤",
        photo: "assets/images/post/4.jpeg",
        date: "1 giờ trước",
        userId: 5,
        like: 45,
        comment: 10,
        share: 0,
    },
    {
        id: 5,
        desc: "uWu",
        photo: "assets/images/post/5.jpeg",
        date: "4 giờ trước",
        userId: 4,
        like: 356,
        comment: 60,
        share: 2,
    },
    {
        id: 6,
        desc: "I meow u ^^",
        photo: "assets/images/post/6.jpeg",
        date: "5 giờ trước",
        userId: 3,
        like: 95,
        comment: 30,
        share: 0,
    },
    {
        id: 7,
        desc: "Hello!",
        photo: "assets/images/post/7.jpeg",
        date: "5 giờ trước",
        userId: 7,
        like: 102,
        comment: 9,
        share: 0,
    },
    {
        id: 8,
        desc: "Hello!",
        photo: "assets/images/post/8.jpeg",
        date: "1 ngày trước",
        userId: 10,
        like: 30,
        comment: 0,
        share: 0,
    },
    {
        id: 9,
        desc: "Green",
        photo: "assets/images/post/9.jpeg",
        date: "1 ngày trước",
        userId: 9,
        like: 87,
        comment: 28,
        share: 0,
    },
    {
        id: 10,
        desc: "Chill!",
        photo: "assets/images/post/10.jpeg",
        date: "1 ngày trước",
        userId: 8,
        like: 98,
        comment: 27,
        share: 0,
    }
];